version: 2
project_name: awsec
before:
  hooks:
    - go mod download

builds:
  -
    id: "client"
    dir: "."
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"

archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - policies/*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: awsec
    repository:
      owner: grimdork
      name: homebrew-tools
    commit_author:
      name: Grimdork
      email: github@grimdork.net
    homepage: "https://github.com/grimdork/awsec"
    description: "Store secrets in AWS Parameter Store."
    license: "MIT"

nfpms:
  - package_name: awsec
    vendor: "grimdork.net"
    maintainer: "Grimdork <github@grimdork.net>"
    homepage: "https://github.com/grimdork/awsec"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: contrib
    priority: extra
    contents:
      - src: LICENSE
        dst: /usr/share/doc/awsec/LICENSE
      - src: README.md
        dst: /usr/share/doc/awsec/README.md
      - src: policies/*
        dst: /usr/share/doc/awsec/examples/policies/

checksum:
  name_template: 'checksums.txt'

signs:
  - id: gpg-sign
    cmd: gpg
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    artifacts: binary
